name: plotwist

services:
  app:
    container_name: plotwist_app
    image: plotwist-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - db
      - redis
      - localstack
    env_file:
      - .env
    networks:
      - plotwist_network

  db:
    container_name: plotwist_db
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES_DB
      POSTGRESQL_REPLICATION_USE_PASSFILE: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./priv/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
    networks:
      - plotwist_network

  redis:
    container_name: plotwist_redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data
    networks:
      - plotwist_network

  localstack:
    image: localstack/localstack
    container_name: plotwist_localstack
    ports:
      - "4566:4566"
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - plotwist_network

  grafana:
    image: grafana/grafana:latest
    container_name: plotwist_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - jaeger
    volumes:
      - ./config/provisioning:/etc/grafana/provisioning
    networks:
      - plotwist_network

  jaeger:
    container_name: plotwist_jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "4318:4318"
    networks:
      - plotwist_network
  # loki:
  #   container_name: plotwist_loki
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - plotwist_network

  # prometheus:
  #   container_name: plotwist_prometheus
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./config/prometheus:/etc/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   networks:
  #     - plotwist_network

volumes:
  postgres_data:
  redis-data:
  localstack_data:


networks:
  plotwist_network:
    driver: bridge
