name: plotwist

services:
  db:
    container_name: plotwist_db
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./priv/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
