# fly.toml app configuration file generated for plotwist-backend on 2024-11-29T23:07:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "plotwist-backend"
app = 'plotwist-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
