metrics:
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://localhost:3001/api/prom/push
        basic_auth:
          username: admin
          password: admin

traces:
  configs:
    - name: default
      receivers:
        otlp:
          protocols:
            http:
              endpoint: "0.0.0.0:4318"
      remote_write:
        - endpoint: localhost:3001
          basic_auth:
            username: admin
            password: admin
      batch:
        timeout: 5s
        send_batch_size: 1000

integrations:
  node_exporter:
    enabled: true 