name: CI/CD
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: plotwist_test

    redis:
      image: bitnami/redis:latest
      ports:
        - "6379:6379"
      environment:
        - REDIS_PASSWORD=redis

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.33

      - name: Install
        run: bun install

      - name: Test
        run: bun run test
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/plotwist_test"

      - name: Types
        run: bun run typecheck

      - name: Build
        run: bun run build
