name: CI/CD
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: testing
          POSTGRESQL_PASSWORD: testing
          POSTGRESQL_DATABASE: testing

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.33

      - name: Install
        run: bun install

      - name: Test
        run: bun run test
        env:
          DATABASE_URL: "postgresql://testing:testing@localhost:5432/testing"

      - name: Types
        run: bun run typecheck

      - name: Build
        run: bun run build

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}
