name: CI/CD
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: plotwist_test
          POSTGRESQL_REPLICATION_USE_PASSFILE: "no"

      redis:
        image: bitnami/redis:latest
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: redis
          
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4576:4576
        environment:
          - SERVICES=sqs
          - DOCKER_HOST=unix:///var/run/docker.sock

    steps:
      - uses: actions/checkout@v4

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Pretest
        run: pnpm run pretest

      - name: Test
        run: pnpm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/plotwist_test
          REDIS_URL: redis://default:redis@127.0.0.1:6379

      - name: Types
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
