name: CI/CD

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.33

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install
        run: bun install

      - name: Start Test Database
        run: docker-compose -f docker-compose.test.yaml up -d

      - name: Wait for Database
        run: sleep 15

      - name: Test
        run: bun run test

      - name: Stop Test Database
        run: docker-compose down

      - name: Types
        run: bun run typecheck

      - name: Build
        run: bun run build

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}
